### ISSUE TITLE
Failed at favicons script

### ISSUE THREAD

**Issue by iamryanyu** [dmnsgn/frontend-boilerplate#20]
Hi there,

With Webpack version, when I run `npm run dev`, I am receiving this error.

https://www.dropbox.com/s/hr8zupkqvs0546n/favicon-error.png?dl=0

Could you please let me know how I can fix this issue?

**Comment by dmnsgn** [comment]
Can you provide the full text log of the error? This screenshot isn't really helping.
`There is likely additional logging output above`

**Comment by iamryanyu** [comment]
I was trying to re-install the boilerplate but now I cannot even install it.

Here is the log: https://www.dropbox.com/s/c4f4p1dixxuums6/2017-09-05T23_44_13_234Z-debug.log?dl=0

Node version: v8.4.0
NPM version: 5.3.0

Thanks a lot!

**Comment by dmnsgn** [comment]
`17663 verbose stack Error: Cannot find module 'fstream'` 
It looks more like an issue with Node: https://github.com/npm/npm/issues/3282

**Comment by iamryanyu** [comment]
Thanks, and now I am getting the favicon error.

The log file can be found here:
https://www.dropbox.com/s/l5f3c6an2306sq9/2017-09-07T10_38_38_585Z-debug.log?dl=0

Thanks a lot!

**Comment by dmnsgn** [comment]
Do you already have a server or something running on port 8080 ?
If yes, you might want to change it here: https://github.com/dmnsgn/frontend-boilerplate/blob/master/config/server.js#L28

**Comment by natezerk** [comment]
I also get this error just cloning the project, installing packages and running dev script.
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'dev' ]
2 info using npm@5.3.0
3 info using node@v7.10.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle frontend-boilerplate@2.0.0~predev: frontend-boilerplate@2.0.0
6 info lifecycle frontend-boilerplate@2.0.0~dev: frontend-boilerplate@2.0.0
7 verbose lifecycle frontend-boilerplate@2.0.0~dev: unsafe-perm in lifecycle true
8 verbose lifecycle frontend-boilerplate@2.0.0~dev: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/nate/Documents/expirysmart/public/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:~/.composer/vendor/bin:/usr/local/CrossPack-AVR/bin:/Users/nate/bin/FDK/Tools/osx
9 verbose lifecycle frontend-boilerplate@2.0.0~dev: CWD: /Users/nate/Documents/expirysmart/public
10 silly lifecycle frontend-boilerplate@2.0.0~dev: Args: [ '-c', 'run-p favicons dev:*' ]
11 silly lifecycle frontend-boilerplate@2.0.0~dev: Returned: code: 1  signal: null
12 info lifecycle frontend-boilerplate@2.0.0~dev: Failed to exec dev script
13 verbose stack Error: frontend-boilerplate@2.0.0 dev: `run-p favicons dev:*`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:289:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at EventEmitter.emit (events.js:194:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:194:7)
13 verbose stack     at maybeClose (internal/child_process.js:899:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
14 verbose pkgid frontend-boilerplate@2.0.0
15 verbose cwd /Users/nate/Documents/expirysmart/public
16 verbose Darwin 16.7.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
18 verbose node v7.10.0
19 verbose npm  v5.3.0
20 error code ELIFECYCLE
21 error errno 1
22 error frontend-boilerplate@2.0.0 dev: `run-p favicons dev:*`
22 error Exit status 1
23 error Failed at the frontend-boilerplate@2.0.0 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by natezerk** [comment]
Looks like a v2 issue to me, rolled back to 1.6.2 and there's no issues.

**Comment by dmnsgn** [comment]
I'd suggest trying this:

```bash
rm -rf node_modules
rm package-lock.json
npm cache clear --force
npm install
```

**Comment by natezerk** [comment]
Thanks for that.
Interestingly first `npm install` failed, and that's when `npm run dev` didn't work.
Running `npm install` again succeeded, and the dev script works fine now.
Before I was also using Yarn.

**Comment by dmnsgn** [comment]
I also updated the dev dependencies in https://github.com/dmnsgn/frontend-boilerplate/releases/tag/2.1.0 just in case but I don't get these errors with node v8.2.1 and npm 5.3.0.

**Comment by dmnsgn** [comment]
@natezerk I'd recommend sticking with npm: the latest version caught up a lot with yarns' features.
Good news if it worked after 2 consecutive `npm install` though.

**Comment by natezerk** [comment]
Thanks a lot. Just used to using Yarn by habit now, npm was behind for so long. Great boilerplate too. Would have taken a lot of time. Will be very handy.
