### ISSUE TITLE
npm run dev error

### ISSUE THREAD

**Issue by ismayil097** [dmnsgn/frontend-boilerplate#21]
Error: [git-rev-sync] failed to execute command: fatal: Not a git repository (or any of the parent directories): .git

    at _command (C:\Users\Iso\Desktop\frontend-boilerplate\node_modules\git-rev-sync\index.js:20:13)
    at Object.count (C:\Users\Iso\Desktop\frontend-boilerplate\node_modules\git-rev-sync\index.js:151:19)
    at Object.<anonymous> (C:\Users\Iso\Desktop\frontend-boilerplate\config\config.js:18:34)
    at Object.<anonymous> (C:\Users\Iso\Desktop\frontend-boilerplate\config\config.js)

**Comment by dmnsgn** [comment]
You need to be in a git repository. Run `git init`.

Alternatively, comment:
```js
import GitRevSync from "git-rev-sync";
```
and replace `GitRevSync` function calls here in `config/config.js`: https://github.com/dmnsgn/frontend-boilerplate/blob/master/config/config.js#L17

**Comment by iamryanyu** [comment]
I have done the `git init` but I am still getting the same error...

For your above comment:

> and replace GitRevSync function calls here in config/config.js: 

I am not quite sure what to replace `GitRevSync` with?

**Comment by dmnsgn** [comment]
If you don't want to rely on having a git repo:

```js
// import GitRevSync from "git-rev-sync";
```

```js
const GIT_INFO = new Map()
  .set("GIT_VERSION", "")
  .set("GIT_DATE", "")
  .set("GIT_TAG", "")
  .set("GIT_HASH", "");
```
